### ISSUE TITLE
Not working with WSL 2 based engine

### ISSUE THREAD

**Issue by justinkb** [kekru/docker-remote-api-tls#8]
It seems like /var/run/docker.sock can't be bind-mounted correctly with that setup. A workaround that should work is to set up the proxy inside the WSL instance itself, behind the docker-desktop-proxy Docker Desktop internally uses there (yeah, it's proxies all the way down)

N.B. my use case is allowing JetBrains software (which can't be configured to use the named pipe Docker Desktop uses) to interface with my local Docker server, without exposing the daemon through the insecure HTTP connection on TCP port 2375

**Comment by justinkb** [comment]
Disregard this, it not working was caused by.. a typo

**Comment by kekru** [comment]
Good to know, that it works on WSL 2 :)
I do not yet have the newest Windows version, so I could not test ist yet
