### ISSUE TITLE
Support hosts without domain names

### ISSUE THREAD

**Issue by hombit** [kekru/docker-remote-api-tls#9]
Now, if i trying to use auto-generated certs with an IP-address instead of domain name, docker raises an error
```
error during connect: Get https://192.168.1.1:2376/v1.40/containers/json: x509: cannot validate certificate for 192.168.1.1 because it doesn't contain any IP SANs
```

Please, add possibility to deal with IP-address as host main address and identifier

**Comment by kekru** [comment]
Hi @hombit,
I never tried using an IP address.

Did you try to use your IP address with the envvar from the Readme.md?  

```bash
CERT_HOSTNAME=192.168.1.1
```

If it does not work, a workaround would be the free DNS service of nip.io

Just replace your IP address with the following, for example:  

```bash
CERT_HOSTNAME=remote-api.192-168-1-1.nip.io
```

This DNS name will resolve to the IP address 192.168.1.1

**Comment by hombit** [comment]
Thank you for your answer.

Yes, I try to use IP-address as hostname, it doesn't work for me.

Formerly I used [Docker Machine](https://github.com/docker/machine) to set up remote Docker access, and it could generate certificates for both cases of hostname and IP-address. Unfortunately Docker Machine is deprecated now and I try to find its replacement for certificate generation.

Thank you for a trick with `nip.io`
